C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
C:\Users\unive\AppData\Local\Programs\Python\Python313\python.exe: can't open file 'C:\\Users\\unive\\Desktop\\v_infinity\\adaptive_dca_ai\\runner_health.py': [Errno 2] No such file or directory
